// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Big Data
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package deepsea.convert_customer_final_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

@SuppressWarnings("unused")
/**
 * Job: Convert_Customer_Final Purpose: <br>
 * Description:  <br>
 * @author romualdrousseau@gmail.com
 * @version 7.0.1.20180411_1414
 * @status 
 */
public class Convert_Customer_Final implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private Object[] multiThreadLockWrite = new Object[0];

	private final static String defaultCharset = java.nio.charset.Charset
			.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

		}

	}

	private ContextProperties context = new ContextProperties();

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "Convert_Customer_Final";
	private final String projectName = "DEEPSEA";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Object>());

	private final java.util.Map<String, Long> start_Hash = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Long>());
	private final java.util.Map<String, Long> end_Hash = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Long>());
	private final java.util.Map<String, Boolean> ok_Hash = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Boolean>());
	public final java.util.List<String[]> globalBuffer = java.util.Collections
			.synchronizedList(new java.util.ArrayList<String[]>());

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(
			java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources
				.entrySet()) {
			talendDataSources.put(
					dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry
							.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap
				.put(KEY_DB_DATASOURCES_RAW,
						new java.util.HashMap<String, javax.sql.DataSource>(
								dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(
			new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent,
				final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null
						&& currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE",
							getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE",
						getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent
						+ " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					Convert_Customer_Final.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass()
							.getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(Convert_Customer_Final.this, new Object[] {
									e, currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void tFileInputExcel_1_error(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		((java.util.Map) threadLocal.get()).put("status", "failure");

		tFileInputExcel_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMap_2_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		((java.util.Map) threadLocal.get()).put("status", "failure");

		tFileInputExcel_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tNormalize_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		((java.util.Map) threadLocal.get()).put("status", "failure");

		tFileInputExcel_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogRow_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		((java.util.Map) threadLocal.get()).put("status", "failure");

		tFileInputExcel_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFileInputExcel_1_onSubJobError(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class row2Struct implements
			routines.system.IPersistableRow<row2Struct> {
		final static byte[] commonByteArrayLock_DEEPSEA_Convert_Customer_Final = new byte[0];
		static byte[] commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[0];

		public String servierCode;

		public String getServierCode() {
			return this.servierCode;
		}

		public String providerCode;

		public String getProviderCode() {
			return this.providerCode;
		}

		public String geographyCode;

		public String getGeographyCode() {
			return this.geographyCode;
		}

		public String sourceChannelCode;

		public String getSourceChannelCode() {
			return this.sourceChannelCode;
		}

		public String nameEn;

		public String getNameEn() {
			return this.nameEn;
		}

		public String nameLo;

		public String getNameLo() {
			return this.nameLo;
		}

		public String geographyCoef;

		public String getGeographyCoef() {
			return this.geographyCoef;
		}

		public String splitNumber;

		public String getSplitNumber() {
			return this.splitNumber;
		}

		public String attribute1;

		public String getAttribute1() {
			return this.attribute1;
		}

		public String attribute2;

		public String getAttribute2() {
			return this.attribute2;
		}

		public String attribute3;

		public String getAttribute3() {
			return this.attribute3;
		}

		public String attribute4;

		public String getAttribute4() {
			return this.attribute4;
		}

		public String attribute5;

		public String getAttribute5() {
			return this.attribute5;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DEEPSEA_Convert_Customer_Final.length) {
					if (length < 1024
							&& commonByteArray_DEEPSEA_Convert_Customer_Final.length == 0) {
						commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[1024];
					} else {
						commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DEEPSEA_Convert_Customer_Final,
						0, length);
				strReturn = new String(
						commonByteArray_DEEPSEA_Convert_Customer_Final, 0,
						length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DEEPSEA_Convert_Customer_Final) {

				try {

					int length = 0;

					this.servierCode = readString(dis);

					this.providerCode = readString(dis);

					this.geographyCode = readString(dis);

					this.sourceChannelCode = readString(dis);

					this.nameEn = readString(dis);

					this.nameLo = readString(dis);

					this.geographyCoef = readString(dis);

					this.splitNumber = readString(dis);

					this.attribute1 = readString(dis);

					this.attribute2 = readString(dis);

					this.attribute3 = readString(dis);

					this.attribute4 = readString(dis);

					this.attribute5 = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.servierCode, dos);

				// String

				writeString(this.providerCode, dos);

				// String

				writeString(this.geographyCode, dos);

				// String

				writeString(this.sourceChannelCode, dos);

				// String

				writeString(this.nameEn, dos);

				// String

				writeString(this.nameLo, dos);

				// String

				writeString(this.geographyCoef, dos);

				// String

				writeString(this.splitNumber, dos);

				// String

				writeString(this.attribute1, dos);

				// String

				writeString(this.attribute2, dos);

				// String

				writeString(this.attribute3, dos);

				// String

				writeString(this.attribute4, dos);

				// String

				writeString(this.attribute5, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("servierCode=" + servierCode);
			sb.append(",providerCode=" + providerCode);
			sb.append(",geographyCode=" + geographyCode);
			sb.append(",sourceChannelCode=" + sourceChannelCode);
			sb.append(",nameEn=" + nameEn);
			sb.append(",nameLo=" + nameLo);
			sb.append(",geographyCoef=" + geographyCoef);
			sb.append(",splitNumber=" + splitNumber);
			sb.append(",attribute1=" + attribute1);
			sb.append(",attribute2=" + attribute2);
			sb.append(",attribute3=" + attribute3);
			sb.append(",attribute4=" + attribute4);
			sb.append(",attribute5=" + attribute5);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row2Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row4Struct implements
			routines.system.IPersistableRow<row4Struct> {
		final static byte[] commonByteArrayLock_DEEPSEA_Convert_Customer_Final = new byte[0];
		static byte[] commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[0];

		public String servierCode;

		public String getServierCode() {
			return this.servierCode;
		}

		public String providerCode;

		public String getProviderCode() {
			return this.providerCode;
		}

		public String geographyCode;

		public String getGeographyCode() {
			return this.geographyCode;
		}

		public String sourceChannelCode;

		public String getSourceChannelCode() {
			return this.sourceChannelCode;
		}

		public String nameEn;

		public String getNameEn() {
			return this.nameEn;
		}

		public String nameLo;

		public String getNameLo() {
			return this.nameLo;
		}

		public String geographyCoef;

		public String getGeographyCoef() {
			return this.geographyCoef;
		}

		public String splitNumber;

		public String getSplitNumber() {
			return this.splitNumber;
		}

		public String attribute1;

		public String getAttribute1() {
			return this.attribute1;
		}

		public String attribute2;

		public String getAttribute2() {
			return this.attribute2;
		}

		public String attribute3;

		public String getAttribute3() {
			return this.attribute3;
		}

		public String attribute4;

		public String getAttribute4() {
			return this.attribute4;
		}

		public String attribute5;

		public String getAttribute5() {
			return this.attribute5;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DEEPSEA_Convert_Customer_Final.length) {
					if (length < 1024
							&& commonByteArray_DEEPSEA_Convert_Customer_Final.length == 0) {
						commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[1024];
					} else {
						commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DEEPSEA_Convert_Customer_Final,
						0, length);
				strReturn = new String(
						commonByteArray_DEEPSEA_Convert_Customer_Final, 0,
						length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DEEPSEA_Convert_Customer_Final) {

				try {

					int length = 0;

					this.servierCode = readString(dis);

					this.providerCode = readString(dis);

					this.geographyCode = readString(dis);

					this.sourceChannelCode = readString(dis);

					this.nameEn = readString(dis);

					this.nameLo = readString(dis);

					this.geographyCoef = readString(dis);

					this.splitNumber = readString(dis);

					this.attribute1 = readString(dis);

					this.attribute2 = readString(dis);

					this.attribute3 = readString(dis);

					this.attribute4 = readString(dis);

					this.attribute5 = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.servierCode, dos);

				// String

				writeString(this.providerCode, dos);

				// String

				writeString(this.geographyCode, dos);

				// String

				writeString(this.sourceChannelCode, dos);

				// String

				writeString(this.nameEn, dos);

				// String

				writeString(this.nameLo, dos);

				// String

				writeString(this.geographyCoef, dos);

				// String

				writeString(this.splitNumber, dos);

				// String

				writeString(this.attribute1, dos);

				// String

				writeString(this.attribute2, dos);

				// String

				writeString(this.attribute3, dos);

				// String

				writeString(this.attribute4, dos);

				// String

				writeString(this.attribute5, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("servierCode=" + servierCode);
			sb.append(",providerCode=" + providerCode);
			sb.append(",geographyCode=" + geographyCode);
			sb.append(",sourceChannelCode=" + sourceChannelCode);
			sb.append(",nameEn=" + nameEn);
			sb.append(",nameLo=" + nameLo);
			sb.append(",geographyCoef=" + geographyCoef);
			sb.append(",splitNumber=" + splitNumber);
			sb.append(",attribute1=" + attribute1);
			sb.append(",attribute2=" + attribute2);
			sb.append(",attribute3=" + attribute3);
			sb.append(",attribute4=" + attribute4);
			sb.append(",attribute5=" + attribute5);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row4Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row1Struct implements
			routines.system.IPersistableRow<row1Struct> {
		final static byte[] commonByteArrayLock_DEEPSEA_Convert_Customer_Final = new byte[0];
		static byte[] commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[0];

		public String servierCode;

		public String getServierCode() {
			return this.servierCode;
		}

		public String providerCode;

		public String getProviderCode() {
			return this.providerCode;
		}

		public String geographyCode;

		public String getGeographyCode() {
			return this.geographyCode;
		}

		public String sourceChannelCode;

		public String getSourceChannelCode() {
			return this.sourceChannelCode;
		}

		public String nameEn;

		public String getNameEn() {
			return this.nameEn;
		}

		public String nameLo;

		public String getNameLo() {
			return this.nameLo;
		}

		public String geographyCoef;

		public String getGeographyCoef() {
			return this.geographyCoef;
		}

		public String splitNumber;

		public String getSplitNumber() {
			return this.splitNumber;
		}

		public String attribute1;

		public String getAttribute1() {
			return this.attribute1;
		}

		public String attribute2;

		public String getAttribute2() {
			return this.attribute2;
		}

		public String attribute3;

		public String getAttribute3() {
			return this.attribute3;
		}

		public String attribute4;

		public String getAttribute4() {
			return this.attribute4;
		}

		public String attribute5;

		public String getAttribute5() {
			return this.attribute5;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DEEPSEA_Convert_Customer_Final.length) {
					if (length < 1024
							&& commonByteArray_DEEPSEA_Convert_Customer_Final.length == 0) {
						commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[1024];
					} else {
						commonByteArray_DEEPSEA_Convert_Customer_Final = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DEEPSEA_Convert_Customer_Final,
						0, length);
				strReturn = new String(
						commonByteArray_DEEPSEA_Convert_Customer_Final, 0,
						length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DEEPSEA_Convert_Customer_Final) {

				try {

					int length = 0;

					this.servierCode = readString(dis);

					this.providerCode = readString(dis);

					this.geographyCode = readString(dis);

					this.sourceChannelCode = readString(dis);

					this.nameEn = readString(dis);

					this.nameLo = readString(dis);

					this.geographyCoef = readString(dis);

					this.splitNumber = readString(dis);

					this.attribute1 = readString(dis);

					this.attribute2 = readString(dis);

					this.attribute3 = readString(dis);

					this.attribute4 = readString(dis);

					this.attribute5 = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.servierCode, dos);

				// String

				writeString(this.providerCode, dos);

				// String

				writeString(this.geographyCode, dos);

				// String

				writeString(this.sourceChannelCode, dos);

				// String

				writeString(this.nameEn, dos);

				// String

				writeString(this.nameLo, dos);

				// String

				writeString(this.geographyCoef, dos);

				// String

				writeString(this.splitNumber, dos);

				// String

				writeString(this.attribute1, dos);

				// String

				writeString(this.attribute2, dos);

				// String

				writeString(this.attribute3, dos);

				// String

				writeString(this.attribute4, dos);

				// String

				writeString(this.attribute5, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("servierCode=" + servierCode);
			sb.append(",providerCode=" + providerCode);
			sb.append(",geographyCode=" + geographyCode);
			sb.append(",sourceChannelCode=" + sourceChannelCode);
			sb.append(",nameEn=" + nameEn);
			sb.append(",nameLo=" + nameLo);
			sb.append(",geographyCoef=" + geographyCoef);
			sb.append(",splitNumber=" + splitNumber);
			sb.append(",attribute1=" + attribute1);
			sb.append(",attribute2=" + attribute2);
			sb.append(",attribute3=" + attribute3);
			sb.append(",attribute4=" + attribute4);
			sb.append(",attribute5=" + attribute5);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tFileInputExcel_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tFileInputExcel_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception()
						.getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row1Struct row1 = new row1Struct();
				row4Struct row4 = new row4Struct();
				row2Struct row2 = new row2Struct();

				/**
				 * [tLogRow_1 begin ] start
				 */

				ok_Hash.put("tLogRow_1", false);
				start_Hash.put("tLogRow_1", System.currentTimeMillis());

				currentComponent = "tLogRow_1";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						runStat.updateStatOnConnection("row2" + iterateId, 0, 0);

					}
				}

				int tos_count_tLogRow_1 = 0;

				class BytesLimit65535_tLogRow_1 {
					public void limitLog4jByte() throws Exception {

					}
				}

				new BytesLimit65535_tLogRow_1().limitLog4jByte();

				// /////////////////////

				final String OUTPUT_FIELD_SEPARATOR_tLogRow_1 = "|";
				java.io.PrintStream consoleOut_tLogRow_1 = null;

				StringBuilder strBuffer_tLogRow_1 = null;
				int nb_line_tLogRow_1 = 0;
				// /////////////////////

				/**
				 * [tLogRow_1 begin ] stop
				 */

				/**
				 * [tNormalize_1 begin ] start
				 */

				ok_Hash.put("tNormalize_1", false);
				start_Hash.put("tNormalize_1", System.currentTimeMillis());

				currentComponent = "tNormalize_1";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						runStat.updateStatOnConnection("row4" + iterateId, 0, 0);

					}
				}

				int tos_count_tNormalize_1 = 0;

				class BytesLimit65535_tNormalize_1 {
					public void limitLog4jByte() throws Exception {

					}
				}

				new BytesLimit65535_tNormalize_1().limitLog4jByte();

				int nb_line_tNormalize_1 = 0;
				String tmp_tNormalize_1 = null;
				StringBuilder currentRecord_tNormalize_1 = null;
				String[] normalizeRecord_tNormalize_1 = null;
				java.util.Set<String> recordSet_tNormalize_1 = new java.util.HashSet<String>();

				/**
				 * [tNormalize_1 begin ] stop
				 */

				/**
				 * [tMap_2 begin ] start
				 */

				ok_Hash.put("tMap_2", false);
				start_Hash.put("tMap_2", System.currentTimeMillis());

				currentComponent = "tMap_2";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						runStat.updateStatOnConnection("row1" + iterateId, 0, 0);

					}
				}

				int tos_count_tMap_2 = 0;

				class BytesLimit65535_tMap_2 {
					public void limitLog4jByte() throws Exception {

					}
				}

				new BytesLimit65535_tMap_2().limitLog4jByte();

				// ###############################
				// # Lookup's keys initialization
				// ###############################

				// ###############################
				// # Vars initialization
				class Var__tMap_2__Struct {
				}
				Var__tMap_2__Struct Var__tMap_2 = new Var__tMap_2__Struct();
				// ###############################

				// ###############################
				// # Outputs initialization
				row4Struct row4_tmp = new row4Struct();
				// ###############################

				/**
				 * [tMap_2 begin ] stop
				 */

				/**
				 * [tFileInputExcel_1 begin ] start
				 */

				ok_Hash.put("tFileInputExcel_1", false);
				start_Hash.put("tFileInputExcel_1", System.currentTimeMillis());

				currentComponent = "tFileInputExcel_1";

				int tos_count_tFileInputExcel_1 = 0;

				class BytesLimit65535_tFileInputExcel_1 {
					public void limitLog4jByte() throws Exception {

					}
				}

				new BytesLimit65535_tFileInputExcel_1().limitLog4jByte();

				class RegexUtil_tFileInputExcel_1 {

					public java.util.List<org.apache.poi.xssf.usermodel.XSSFSheet> getSheets(
							org.apache.poi.xssf.usermodel.XSSFWorkbook workbook,
							String oneSheetName, boolean useRegex) {

						java.util.List<org.apache.poi.xssf.usermodel.XSSFSheet> list = new java.util.ArrayList<org.apache.poi.xssf.usermodel.XSSFSheet>();

						if (useRegex) {// this part process the regex issue

							java.util.regex.Pattern pattern = java.util.regex.Pattern
									.compile(oneSheetName);
							for (org.apache.poi.ss.usermodel.Sheet sheet : workbook) {
								String sheetName = sheet.getSheetName();
								java.util.regex.Matcher matcher = pattern
										.matcher(sheetName);
								if (matcher.matches()) {
									if (sheet != null) {
										list.add((org.apache.poi.xssf.usermodel.XSSFSheet) sheet);
									}
								}
							}

						} else {
							org.apache.poi.xssf.usermodel.XSSFSheet sheet = (org.apache.poi.xssf.usermodel.XSSFSheet) workbook
									.getSheet(oneSheetName);
							if (sheet != null) {
								list.add(sheet);
							}

						}

						return list;
					}

					public java.util.List<org.apache.poi.xssf.usermodel.XSSFSheet> getSheets(
							org.apache.poi.xssf.usermodel.XSSFWorkbook workbook,
							int index, boolean useRegex) {
						java.util.List<org.apache.poi.xssf.usermodel.XSSFSheet> list = new java.util.ArrayList<org.apache.poi.xssf.usermodel.XSSFSheet>();
						org.apache.poi.xssf.usermodel.XSSFSheet sheet = (org.apache.poi.xssf.usermodel.XSSFSheet) workbook
								.getSheetAt(index);
						if (sheet != null) {
							list.add(sheet);
						}
						return list;
					}

				}
				RegexUtil_tFileInputExcel_1 regexUtil_tFileInputExcel_1 = new RegexUtil_tFileInputExcel_1();

				Object source_tFileInputExcel_1 = "/run/media/romuald/34AA-69EB/master/Customer.xlsx";
				org.apache.poi.xssf.usermodel.XSSFWorkbook workbook_tFileInputExcel_1 = null;

				if (source_tFileInputExcel_1 instanceof String) {
					workbook_tFileInputExcel_1 = new org.apache.poi.xssf.usermodel.XSSFWorkbook(
							(String) source_tFileInputExcel_1);
				} else if (source_tFileInputExcel_1 instanceof java.io.InputStream) {
					workbook_tFileInputExcel_1 = new org.apache.poi.xssf.usermodel.XSSFWorkbook(
							(java.io.InputStream) source_tFileInputExcel_1);
				} else {
					workbook_tFileInputExcel_1 = null;
					throw new java.lang.Exception(
							"The data source should be specified as Inputstream or File Path!");
				}
				try {

					java.util.List<org.apache.poi.xssf.usermodel.XSSFSheet> sheetList_tFileInputExcel_1 = new java.util.ArrayList<org.apache.poi.xssf.usermodel.XSSFSheet>();
					sheetList_tFileInputExcel_1
							.addAll(regexUtil_tFileInputExcel_1.getSheets(
									workbook_tFileInputExcel_1, "ZUELLIG",
									false));
					if (sheetList_tFileInputExcel_1.size() <= 0) {
						throw new RuntimeException("Special sheets not exist!");
					}

					java.util.List<org.apache.poi.xssf.usermodel.XSSFSheet> sheetList_FilterNull_tFileInputExcel_1 = new java.util.ArrayList<org.apache.poi.xssf.usermodel.XSSFSheet>();
					for (org.apache.poi.xssf.usermodel.XSSFSheet sheet_FilterNull_tFileInputExcel_1 : sheetList_tFileInputExcel_1) {
						if (sheet_FilterNull_tFileInputExcel_1 != null
								&& sheetList_FilterNull_tFileInputExcel_1
										.iterator() != null
								&& sheet_FilterNull_tFileInputExcel_1
										.iterator().hasNext()) {
							sheetList_FilterNull_tFileInputExcel_1
									.add(sheet_FilterNull_tFileInputExcel_1);
						}
					}
					sheetList_tFileInputExcel_1 = sheetList_FilterNull_tFileInputExcel_1;
					if (sheetList_tFileInputExcel_1.size() > 0) {
						int nb_line_tFileInputExcel_1 = 0;

						int begin_line_tFileInputExcel_1 = 1;

						int footer_input_tFileInputExcel_1 = 0;

						int end_line_tFileInputExcel_1 = 0;
						for (org.apache.poi.xssf.usermodel.XSSFSheet sheet_tFileInputExcel_1 : sheetList_tFileInputExcel_1) {
							end_line_tFileInputExcel_1 += (sheet_tFileInputExcel_1
									.getLastRowNum() + 1);
						}
						end_line_tFileInputExcel_1 -= footer_input_tFileInputExcel_1;
						int limit_tFileInputExcel_1 = -1;
						int start_column_tFileInputExcel_1 = 1 - 1;
						int end_column_tFileInputExcel_1 = -1;

						org.apache.poi.xssf.usermodel.XSSFRow row_tFileInputExcel_1 = null;
						org.apache.poi.xssf.usermodel.XSSFSheet sheet_tFileInputExcel_1 = sheetList_tFileInputExcel_1
								.get(0);
						int rowCount_tFileInputExcel_1 = 0;
						int sheetIndex_tFileInputExcel_1 = 0;
						int currentRows_tFileInputExcel_1 = (sheetList_tFileInputExcel_1
								.get(0).getLastRowNum() + 1);

						// for the number format
						java.text.DecimalFormat df_tFileInputExcel_1 = new java.text.DecimalFormat(
								"#.####################################");
						char decimalChar_tFileInputExcel_1 = df_tFileInputExcel_1
								.getDecimalFormatSymbols()
								.getDecimalSeparator();

						for (int i_tFileInputExcel_1 = begin_line_tFileInputExcel_1; i_tFileInputExcel_1 < end_line_tFileInputExcel_1; i_tFileInputExcel_1++) {

							int emptyColumnCount_tFileInputExcel_1 = 0;

							if (limit_tFileInputExcel_1 != -1
									&& nb_line_tFileInputExcel_1 >= limit_tFileInputExcel_1) {
								break;
							}

							while (i_tFileInputExcel_1 >= rowCount_tFileInputExcel_1
									+ currentRows_tFileInputExcel_1) {
								rowCount_tFileInputExcel_1 += currentRows_tFileInputExcel_1;
								sheet_tFileInputExcel_1 = sheetList_tFileInputExcel_1
										.get(++sheetIndex_tFileInputExcel_1);
								currentRows_tFileInputExcel_1 = (sheet_tFileInputExcel_1
										.getLastRowNum() + 1);
							}
							globalMap.put("tFileInputExcel_1_CURRENT_SHEET",
									sheet_tFileInputExcel_1.getSheetName());
							if (rowCount_tFileInputExcel_1 <= i_tFileInputExcel_1) {
								row_tFileInputExcel_1 = sheet_tFileInputExcel_1
										.getRow(i_tFileInputExcel_1
												- rowCount_tFileInputExcel_1);
							}
							row1 = null;
							int tempRowLength_tFileInputExcel_1 = 13;

							int columnIndex_tFileInputExcel_1 = 0;

							String[] temp_row_tFileInputExcel_1 = new String[tempRowLength_tFileInputExcel_1];
							int excel_end_column_tFileInputExcel_1;
							if (row_tFileInputExcel_1 == null) {
								excel_end_column_tFileInputExcel_1 = 0;
							} else {
								excel_end_column_tFileInputExcel_1 = row_tFileInputExcel_1
										.getLastCellNum();
							}
							int actual_end_column_tFileInputExcel_1;
							if (end_column_tFileInputExcel_1 == -1) {
								actual_end_column_tFileInputExcel_1 = excel_end_column_tFileInputExcel_1;
							} else {
								actual_end_column_tFileInputExcel_1 = end_column_tFileInputExcel_1 > excel_end_column_tFileInputExcel_1 ? excel_end_column_tFileInputExcel_1
										: end_column_tFileInputExcel_1;
							}
							org.apache.poi.ss.formula.eval.NumberEval ne_tFileInputExcel_1 = null;
							for (int i = 0; i < tempRowLength_tFileInputExcel_1; i++) {
								if (i + start_column_tFileInputExcel_1 < actual_end_column_tFileInputExcel_1) {
									org.apache.poi.ss.usermodel.Cell cell_tFileInputExcel_1 = row_tFileInputExcel_1
											.getCell(i
													+ start_column_tFileInputExcel_1);
									if (cell_tFileInputExcel_1 != null) {
										switch (cell_tFileInputExcel_1
												.getCellType()) {
										case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_STRING:
											temp_row_tFileInputExcel_1[i] = cell_tFileInputExcel_1
													.getRichStringCellValue()
													.getString();
											break;
										case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_NUMERIC:
											if (org.apache.poi.ss.usermodel.DateUtil
													.isCellDateFormatted(cell_tFileInputExcel_1)) {
												temp_row_tFileInputExcel_1[i] = cell_tFileInputExcel_1
														.getDateCellValue()
														.toString();
											} else {
												temp_row_tFileInputExcel_1[i] = df_tFileInputExcel_1
														.format(cell_tFileInputExcel_1
																.getNumericCellValue());
											}
											break;
										case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_BOOLEAN:
											temp_row_tFileInputExcel_1[i] = String
													.valueOf(cell_tFileInputExcel_1
															.getBooleanCellValue());
											break;
										case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_FORMULA:
											switch (cell_tFileInputExcel_1
													.getCachedFormulaResultType()) {
											case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_STRING:
												temp_row_tFileInputExcel_1[i] = cell_tFileInputExcel_1
														.getRichStringCellValue()
														.getString();
												break;
											case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_NUMERIC:
												if (org.apache.poi.ss.usermodel.DateUtil
														.isCellDateFormatted(cell_tFileInputExcel_1)) {
													temp_row_tFileInputExcel_1[i] = cell_tFileInputExcel_1
															.getDateCellValue()
															.toString();
												} else {
													ne_tFileInputExcel_1 = new org.apache.poi.ss.formula.eval.NumberEval(
															cell_tFileInputExcel_1
																	.getNumericCellValue());
													temp_row_tFileInputExcel_1[i] = ne_tFileInputExcel_1
															.getStringValue();
												}
												break;
											case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_BOOLEAN:
												temp_row_tFileInputExcel_1[i] = String
														.valueOf(cell_tFileInputExcel_1
																.getBooleanCellValue());
												break;
											default:
												temp_row_tFileInputExcel_1[i] = "";
											}
											break;
										default:
											temp_row_tFileInputExcel_1[i] = "";
										}
									} else {
										temp_row_tFileInputExcel_1[i] = "";
									}

								} else {
									temp_row_tFileInputExcel_1[i] = "";
								}
							}
							boolean whetherReject_tFileInputExcel_1 = false;
							row1 = new row1Struct();
							int curColNum_tFileInputExcel_1 = -1;
							String curColName_tFileInputExcel_1 = "";
							try {
								columnIndex_tFileInputExcel_1 = 0;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "servierCode";

									row1.servierCode = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.servierCode = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 1;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "providerCode";

									row1.providerCode = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.providerCode = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 2;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "geographyCode";

									row1.geographyCode = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.geographyCode = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 3;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "sourceChannelCode";

									row1.sourceChannelCode = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.sourceChannelCode = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 4;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "nameEn";

									row1.nameEn = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.nameEn = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 5;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "nameLo";

									row1.nameLo = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.nameLo = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 6;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "geographyCoef";

									row1.geographyCoef = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.geographyCoef = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 7;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "splitNumber";

									row1.splitNumber = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.splitNumber = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 8;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "attribute1";

									row1.attribute1 = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.attribute1 = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 9;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "attribute2";

									row1.attribute2 = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.attribute2 = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 10;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "attribute3";

									row1.attribute3 = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.attribute3 = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 11;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "attribute4";

									row1.attribute4 = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.attribute4 = null;
									emptyColumnCount_tFileInputExcel_1++;
								}
								columnIndex_tFileInputExcel_1 = 12;

								if (temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1]
										.length() > 0) {
									curColNum_tFileInputExcel_1 = columnIndex_tFileInputExcel_1
											+ start_column_tFileInputExcel_1
											+ 1;
									curColName_tFileInputExcel_1 = "attribute5";

									row1.attribute5 = temp_row_tFileInputExcel_1[columnIndex_tFileInputExcel_1];
								} else {
									row1.attribute5 = null;
									emptyColumnCount_tFileInputExcel_1++;
								}

								nb_line_tFileInputExcel_1++;

							} catch (java.lang.Exception e) {
								whetherReject_tFileInputExcel_1 = true;
								System.err.println(e.getMessage());
								row1 = null;
							}

							/**
							 * [tFileInputExcel_1 begin ] stop
							 */

							/**
							 * [tFileInputExcel_1 main ] start
							 */

							currentComponent = "tFileInputExcel_1";

							tos_count_tFileInputExcel_1++;

							/**
							 * [tFileInputExcel_1 main ] stop
							 */

							/**
							 * [tFileInputExcel_1 process_data_begin ] start
							 */

							currentComponent = "tFileInputExcel_1";

							/**
							 * [tFileInputExcel_1 process_data_begin ] stop
							 */
							// Start of branch "row1"
							if (row1 != null) {

								/**
								 * [tMap_2 main ] start
								 */

								currentComponent = "tMap_2";

								// row1
								// row1

								if (execStat) {
									runStat.updateStatOnConnection("row1"
											+ iterateId, 1, 1);
								}

								boolean hasCasePrimitiveKeyWithNull_tMap_2 = false;

								// ###############################
								// # Input tables (lookups)
								boolean rejectedInnerJoin_tMap_2 = false;
								boolean mainRowRejected_tMap_2 = false;

								// ###############################
								{ // start of Var scope

									// ###############################
									// # Vars tables

									Var__tMap_2__Struct Var = Var__tMap_2;// ###############################
									// ###############################
									// # Output tables

									row4 = null;

									// # Output table : 'row4'
									row4_tmp.servierCode = row1.servierCode;
									row4_tmp.providerCode = row1.providerCode;
									row4_tmp.geographyCode = (row1.geographyCode
											.equals("SF")) ? "" : TalendString
											.talendTrim((row1.geographyCode),
													';', 0);
									row4_tmp.sourceChannelCode = row1.sourceChannelCode;
									row4_tmp.nameEn = row1.nameEn;
									row4_tmp.nameLo = row1.nameLo;
									row4_tmp.geographyCoef = row1.geographyCoef;
									row4_tmp.splitNumber = row1.splitNumber;
									row4_tmp.attribute1 = row1.attribute1;
									row4_tmp.attribute2 = row1.attribute2;
									row4_tmp.attribute3 = row1.attribute3;
									row4_tmp.attribute4 = row1.attribute4;
									row4_tmp.attribute5 = row1.attribute5;
									row4 = row4_tmp;
									// ###############################

								} // end of Var scope

								rejectedInnerJoin_tMap_2 = false;

								tos_count_tMap_2++;

								/**
								 * [tMap_2 main ] stop
								 */

								/**
								 * [tMap_2 process_data_begin ] start
								 */

								currentComponent = "tMap_2";

								/**
								 * [tMap_2 process_data_begin ] stop
								 */
								// Start of branch "row4"
								if (row4 != null) {

									/**
									 * [tNormalize_1 main ] start
									 */

									currentComponent = "tNormalize_1";

									// row4
									// row4

									if (execStat) {
										runStat.updateStatOnConnection("row4"
												+ iterateId, 1, 1);
									}

									normalizeRecord_tNormalize_1 = new String[1];
									if (row4.geographyCode != null) {
										if ("".equals(row4.geographyCode)) {
											normalizeRecord_tNormalize_1[0] = "";
										} else {

											normalizeRecord_tNormalize_1 = row4.geographyCode
													.split(";", -1);

										}
									}
									int lastNoEmptyIndex_tNormalize_1 = normalizeRecord_tNormalize_1.length;

									for (int i_tNormalize_1 = 0; i_tNormalize_1 < lastNoEmptyIndex_tNormalize_1; i_tNormalize_1++) {

										currentRecord_tNormalize_1 = new StringBuilder();
										nb_line_tNormalize_1++;

										tmp_tNormalize_1 = row4.servierCode == null ? null
												: String.valueOf(row4.servierCode);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.providerCode == null ? null
												: String.valueOf(row4.providerCode);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										if (normalizeRecord_tNormalize_1[i_tNormalize_1] != null) {
											currentRecord_tNormalize_1
													.append(normalizeRecord_tNormalize_1[i_tNormalize_1]
															+ normalizeRecord_tNormalize_1[i_tNormalize_1]
																	.length());
										}

										tmp_tNormalize_1 = row4.sourceChannelCode == null ? null
												: String.valueOf(row4.sourceChannelCode);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.nameEn == null ? null
												: String.valueOf(row4.nameEn);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.nameLo == null ? null
												: String.valueOf(row4.nameLo);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.geographyCoef == null ? null
												: String.valueOf(row4.geographyCoef);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.splitNumber == null ? null
												: String.valueOf(row4.splitNumber);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.attribute1 == null ? null
												: String.valueOf(row4.attribute1);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.attribute2 == null ? null
												: String.valueOf(row4.attribute2);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.attribute3 == null ? null
												: String.valueOf(row4.attribute3);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.attribute4 == null ? null
												: String.valueOf(row4.attribute4);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										tmp_tNormalize_1 = row4.attribute5 == null ? null
												: String.valueOf(row4.attribute5);

										if (tmp_tNormalize_1 != null) {
											currentRecord_tNormalize_1
													.append(tmp_tNormalize_1
															+ tmp_tNormalize_1
																	.length());
										}

										if (!recordSet_tNormalize_1
												.contains(currentRecord_tNormalize_1
														.toString())) {
											recordSet_tNormalize_1
													.add(currentRecord_tNormalize_1
															.toString());
										} else {
											continue;
										}

										row2.servierCode = row4.servierCode;

										row2.providerCode = row4.providerCode;

										row2.geographyCode = normalizeRecord_tNormalize_1[i_tNormalize_1];

										row2.sourceChannelCode = row4.sourceChannelCode;

										row2.nameEn = row4.nameEn;

										row2.nameLo = row4.nameLo;

										row2.geographyCoef = row4.geographyCoef;

										row2.splitNumber = row4.splitNumber;

										row2.attribute1 = row4.attribute1;

										row2.attribute2 = row4.attribute2;

										row2.attribute3 = row4.attribute3;

										row2.attribute4 = row4.attribute4;

										row2.attribute5 = row4.attribute5;

										tos_count_tNormalize_1++;

										/**
										 * [tNormalize_1 main ] stop
										 */

										/**
										 * [tNormalize_1 process_data_begin ]
										 * start
										 */

										currentComponent = "tNormalize_1";

										/**
										 * [tNormalize_1 process_data_begin ]
										 * stop
										 */

										/**
										 * [tLogRow_1 main ] start
										 */

										currentComponent = "tLogRow_1";

										// row2
										// row2

										if (execStat) {
											runStat.updateStatOnConnection(
													"row2" + iterateId, 1, 1);
										}

										// /////////////////////

										strBuffer_tLogRow_1 = new StringBuilder();

										if (row2.servierCode != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.servierCode));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.providerCode != null) { //

											strBuffer_tLogRow_1
													.append(String
															.valueOf(row2.providerCode));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.geographyCode != null) { //

											strBuffer_tLogRow_1
													.append(String
															.valueOf(row2.geographyCode));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.sourceChannelCode != null) { //

											strBuffer_tLogRow_1
													.append(String
															.valueOf(row2.sourceChannelCode));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.nameEn != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.nameEn));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.nameLo != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.nameLo));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.geographyCoef != null) { //

											strBuffer_tLogRow_1
													.append(String
															.valueOf(row2.geographyCoef));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.splitNumber != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.splitNumber));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.attribute1 != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.attribute1));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.attribute2 != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.attribute2));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.attribute3 != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.attribute3));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.attribute4 != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.attribute4));

										} //

										strBuffer_tLogRow_1.append("|");

										if (row2.attribute5 != null) { //

											strBuffer_tLogRow_1.append(String
													.valueOf(row2.attribute5));

										} //

										if (globalMap.get("tLogRow_CONSOLE") != null) {
											consoleOut_tLogRow_1 = (java.io.PrintStream) globalMap
													.get("tLogRow_CONSOLE");
										} else {
											consoleOut_tLogRow_1 = new java.io.PrintStream(
													new java.io.BufferedOutputStream(
															System.out));
											globalMap.put("tLogRow_CONSOLE",
													consoleOut_tLogRow_1);
										}
										consoleOut_tLogRow_1
												.println(strBuffer_tLogRow_1
														.toString());
										consoleOut_tLogRow_1.flush();
										nb_line_tLogRow_1++;
										// ////

										// ////

										// /////////////////////

										tos_count_tLogRow_1++;

										/**
										 * [tLogRow_1 main ] stop
										 */

										/**
										 * [tLogRow_1 process_data_begin ] start
										 */

										currentComponent = "tLogRow_1";

										/**
										 * [tLogRow_1 process_data_begin ] stop
										 */

										/**
										 * [tLogRow_1 process_data_end ] start
										 */

										currentComponent = "tLogRow_1";

										/**
										 * [tLogRow_1 process_data_end ] stop
										 */
										// end for
									}

									/**
									 * [tNormalize_1 process_data_end ] start
									 */

									currentComponent = "tNormalize_1";

									/**
									 * [tNormalize_1 process_data_end ] stop
									 */

								} // End of branch "row4"

								/**
								 * [tMap_2 process_data_end ] start
								 */

								currentComponent = "tMap_2";

								/**
								 * [tMap_2 process_data_end ] stop
								 */

							} // End of branch "row1"

							/**
							 * [tFileInputExcel_1 process_data_end ] start
							 */

							currentComponent = "tFileInputExcel_1";

							/**
							 * [tFileInputExcel_1 process_data_end ] stop
							 */

							/**
							 * [tFileInputExcel_1 end ] start
							 */

							currentComponent = "tFileInputExcel_1";

						}

						globalMap.put("tFileInputExcel_1_NB_LINE",
								nb_line_tFileInputExcel_1);

					}

				} finally {

					if (!(source_tFileInputExcel_1 instanceof java.io.InputStream)) {
						workbook_tFileInputExcel_1.getPackage().revert();
					}

				}

				ok_Hash.put("tFileInputExcel_1", true);
				end_Hash.put("tFileInputExcel_1", System.currentTimeMillis());

				/**
				 * [tFileInputExcel_1 end ] stop
				 */

				/**
				 * [tMap_2 end ] start
				 */

				currentComponent = "tMap_2";

				// ###############################
				// # Lookup hashes releasing
				// ###############################

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null
							|| !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("row1" + iterateId, 2, 0);
					}
				}

				ok_Hash.put("tMap_2", true);
				end_Hash.put("tMap_2", System.currentTimeMillis());

				/**
				 * [tMap_2 end ] stop
				 */

				/**
				 * [tNormalize_1 end ] start
				 */

				currentComponent = "tNormalize_1";

				globalMap.put("tNormalize_1_NB_LINE", nb_line_tNormalize_1);
				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null
							|| !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("row4" + iterateId, 2, 0);
					}
				}

				ok_Hash.put("tNormalize_1", true);
				end_Hash.put("tNormalize_1", System.currentTimeMillis());

				/**
				 * [tNormalize_1 end ] stop
				 */

				/**
				 * [tLogRow_1 end ] start
				 */

				currentComponent = "tLogRow_1";

				// ////
				// ////
				globalMap.put("tLogRow_1_NB_LINE", nb_line_tLogRow_1);

				// /////////////////////

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null
							|| !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("row2" + iterateId, 2, 0);
					}
				}

				ok_Hash.put("tLogRow_1", true);
				end_Hash.put("tLogRow_1", System.currentTimeMillis());

				/**
				 * [tLogRow_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent,
					globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tFileInputExcel_1 finally ] start
				 */

				currentComponent = "tFileInputExcel_1";

				/**
				 * [tFileInputExcel_1 finally ] stop
				 */

				/**
				 * [tMap_2 finally ] start
				 */

				currentComponent = "tMap_2";

				/**
				 * [tMap_2 finally ] stop
				 */

				/**
				 * [tNormalize_1 finally ] start
				 */

				currentComponent = "tNormalize_1";

				/**
				 * [tNormalize_1 finally ] stop
				 */

				/**
				 * [tLogRow_1 finally ] start
				 */

				currentComponent = "tLogRow_1";

				/**
				 * [tLogRow_1 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tFileInputExcel_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	private SyncInt runningThreadCount = new SyncInt();

	private class SyncInt {
		private int count = 0;

		public synchronized void add(int i) {
			count += i;
		}

		public synchronized int getCount() {
			return count;
		}
	}

	private PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final Convert_Customer_Final Convert_Customer_FinalClass = new Convert_Customer_Final();

		int exitCode = Convert_Customer_FinalClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket
				// can't open
				System.err.println("The statistics socket port " + portStats
						+ " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}

		try {
			// call job/subjob with an existing context, like:
			// --context=production. if without this parameter, there will use
			// the default context instead.
			java.io.InputStream inContext = Convert_Customer_Final.class
					.getClassLoader().getResourceAsStream(
							"deepsea/convert_customer_final_0_1/contexts/"
									+ contextStr + ".properties");
			if (inContext == null) {
				inContext = Convert_Customer_Final.class
						.getClassLoader()
						.getResourceAsStream(
								"config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				// defaultProps is in order to keep the original context value
				defaultProps.load(inContext);
				inContext.close();
				context = new ContextProperties(defaultProps);
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param
				// is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param
							.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil
				.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName,
				jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName,
				parent_part_launcher, Thread.currentThread().getId() + "", "",
				"", "", "",
				resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs
		final Thread launchingThread = Thread.currentThread();
		runningThreadCount.add(1);
		new Thread() {
			public void run() {
				java.util.Map threadRunResultMap = new java.util.HashMap();
				threadRunResultMap.put("errorCode", null);
				threadRunResultMap.put("status", "");
				threadLocal.set(threadRunResultMap);

				try {
					((java.util.Map) threadLocal.get()).put("errorCode", null);
					tFileInputExcel_1Process(globalMap);
					if (!"failure".equals(((java.util.Map) threadLocal.get())
							.get("status"))) {
						((java.util.Map) threadLocal.get())
								.put("status", "end");
					}
				} catch (TalendException e_tFileInputExcel_1) {
					globalMap.put("tFileInputExcel_1_SUBPROCESS_STATE", -1);

					e_tFileInputExcel_1.printStackTrace();

				} catch (java.lang.Error e_tFileInputExcel_1) {
					globalMap.put("tFileInputExcel_1_SUBPROCESS_STATE", -1);
					((java.util.Map) threadLocal.get())
							.put("status", "failure");
					throw e_tFileInputExcel_1;

				} finally {
					Integer localErrorCode = (Integer) (((java.util.Map) threadLocal
							.get()).get("errorCode"));
					String localStatus = (String) (((java.util.Map) threadLocal
							.get()).get("status"));
					if (localErrorCode != null) {
						if (errorCode == null
								|| localErrorCode.compareTo(errorCode) > 0) {
							errorCode = localErrorCode;
						}
					}
					if (!status.equals("failure")) {
						status = localStatus;
					}

					if ("true".equals(((java.util.Map) threadLocal.get())
							.get("JobInterrupted"))) {
						launchingThread.interrupt();
					}

					runningThreadCount.add(-1);
				}
			}
		}.start();

		boolean interrupted = false;
		while (runningThreadCount.getCount() > 0) {
			try {
				Thread.sleep(10);
			} catch (java.lang.InterruptedException e) {
				interrupted = true;
			} catch (java.lang.Exception e) {
				e.printStackTrace();
			}
		}

		if (interrupted) {
			Thread.currentThread().interrupt();
		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		if (false) {
			System.out
					.println((endUsedMemory - startUsedMemory)
							+ " bytes memory increase when running : Convert_Customer_Final");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;
		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher,
				Thread.currentThread().getId() + "", "", "" + returnCode, "",
				"", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index),
							keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index),
							keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		}

	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" },
			{ "\\'", "\'" }, { "\\r", "\r" }, { "\\f", "\f" }, { "\\b", "\b" },
			{ "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex,
							index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left
			// into the result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 82038 characters generated by Talend Open Studio for Big Data on the January
 * 12, 2019 6:02:06 PM CST
 ************************************************************************************************/
